name: Bug report
description: If you encountered an issue with an Unfolded Circle product, please let us know by describing the issue, reproduction steps and any logs you have.
title: '[bug] title'
labels: [bug]

body:
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists for the bug you encountered.
    options:
    - label: I have searched the existing issues
      required: true
- type: textarea
  attributes:
    label: Description
    description: A clear and concise description of what the bug is.
  validations:
    required: true
- type: textarea
  attributes:
    label: How to Reproduce
    description: Steps to reproduce the behavior.
    placeholder: |
      1. Got to '...'
      2. Click on '...'
      3. Scroll down to '...'
      4. See error
  validations:
    required: true
- type: textarea
  attributes:
    label: Expected behavior
    description: A clear and concise description of what you expected to happen.
  validations:
    required: true
- type: input
  id: system_version
  attributes:
    label: System version
    description: You can find the system version under Settings/About
    placeholder: ex. v1.0.6
  validations:
    required: false
- type: dropdown
  id: affected_area
  attributes:
    label: What part of the system affected by the problem?
    multiple: true
    options:
      - UI
      - Core
      - Web Configurator
      - Integration
      - Overall system
- type: textarea
  attributes:
    label: Additional context
    description: |
      Add any other context about the problem here. Otherwise you can delete this section.
      How has this issue affected you? What are you trying to accomplish?
      Providing context helps us come up with a solution that is most useful in the real world

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
