name: Feature request
description: If you have an idea for a feature, please share it with us.
title: '[feature request] title'
labels: [feature request]

body:
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists for the feature request.
    options:
    - label: I have searched the existing issues
      required: true
- type: textarea
  attributes:
    label: Description
    description: A clear and concise description of what the idea is.
  validations:
    required: true
- type: textarea
  attributes:
    label: Additional context
    description: |
      Add any other context about the feature request here. Otherwise you can delete this section.
      Providing context helps us come up with a solution that is most useful in the real world.

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
